#!/bin/bash

ENTRY_POINT="/tmp/dock_traviscli_entry_point.sh"

cat > ${ENTRY_POINT} << EOF
#!/bin/bash
groupadd -g $(getent group $USER | cut -d: -f3) $USER
useradd -m -g $USER -G sudo -N -u $UID $USER
chown $USER:$USER /travis
/bin/su $USER -c "/usr/local/bin/travis $@"

EOF

chmod +x ${ENTRY_POINT}
VOLUMES="-v ${ENTRY_POINT}:${ENTRY_POINT}:ro -v $PWD:/repo -v /tmp/travis:/travis"

docker run --rm -ti --entrypoint=${ENTRY_POINT} ${VOLUMES} approximator/traviscli
rm ${ENTRY_POINT}

# ./TravisCLI/travis login --github-token xxx
# ./TravisCLI/travis env set DOCKER_EMAIL me@example.com
# ./TravisCLI/travis env set DOCKER_USERNAME myusername
# ./TravisCLI/travis env set DOCKER_PASSWORD secretsecret
