#!/bin/bash

: ${VERSION:="latest"}
: ${ADDITIONAL_VOLUMES:=""}

VOLUMES="${ADDITIONAL_VOLUMES} -v $PWD:$PWD -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm"

if [ "/home/$USER" != "$PWD" ]; then
    VOLUMES="${VOLUMES} -v $HOME/dock/clion:/home/$USER"
fi

echo "Volumes: ${VOLUMES}"

docker run -d ${VOLUMES} -e DISPLAY=$DISPLAY -e HOST_USER_ID=$(id -u) -e HOST_USER_GROUP_ID=$(id -g) -e HOST_USER_NAME=$USER approximator/clion:$VERSION /etc/clion/bin/clion.sh "$@"
