FROM ubuntu:focal

ENV DOWNLOAD_URL=https://download.jetbrains.com/cpp/CLion-2020.3.1.tar.gz
ENV CLION_HOME=/etc/clion
ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ADD common/setup.sh /tmp/setup.sh

RUN /tmp/setup.sh                                 \
 && DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    apt-transport-https        \
    build-essential            \
    ca-certificates            \
    git                        \
    libfreetype6-dev           \
    libxft-dev                 \
    libxml2-dev                \
    libxrender1                \
    libxslt1-dev               \
    libxtst6                   \
    openjdk-8-jre              \
    pkg-config                 \
    python3-dev                \
    python3-pip                \
    python3-setuptools         \
    python3.8                  \
    zlib1g-dev                 \
 && apt-get clean              \
                               \
 && python3 -m pip install -U  \
    setuptools wheel virtualenv\
                               \
 && wget -P /tmp/ -O /tmp/clion.tar.gz ${DOWNLOAD_URL}                         \
 && mkdir ${CLION_HOME}                                                        \
 && tar -xzvf /tmp/clion.tar.gz -C ${CLION_HOME} --strip=1                     \
 && chmod +x /usr/local/bin/gosu                                               \
 && cd /tmp/               && find . -delete                                   \
 && cd /var/lib/apt/lists/ && find . -delete                                   \
 && cd /var/tmp/           && find . -delete

RUN python3 -m pip install -U conan

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                                                   \
      org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
