FROM ubuntu:16.04
MAINTAINER alex@nls.la

ADD http://apt.llvm.org/llvm-snapshot.gpg.key /tmp/llvm-snapshot.gpg.key

RUN echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" | tee -a /etc/apt/sources.list \
 && apt-key add /tmp/llvm-snapshot.gpg.key                                    \
 && DEBIAN_FRONTEND=noninteractive apt-get update                             \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        clang-format-4.0                     \
 && apt-get clean                            \
                                             \
 && cd /tmp/               && find . -delete \
 && cd /var/lib/apt/lists/ && find . -delete \
 && cd /var/tmp/           && find . -delete

 ARG BUILD_DATE
 ARG VCS_REF
 LABEL org.label-schema.build-date=$BUILD_DATE                                  \
       org.label-schema.vcs-ref=$VCS_REF                                        \
       org.label-schema.vcs-type="git"                                          \
       org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
