FROM ubuntu:16.10

ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ADD common/setup.sh /tmp/setup.sh
ADD http://apt.llvm.org/llvm-snapshot.gpg.key /tmp/llvm-snapshot.gpg.key

RUN /tmp/setup.sh                                                             \
 && echo "deb http://apt.llvm.org/yakkety/ llvm-toolchain-yakkety-4.0 main" | tee -a /etc/apt/sources.list \
 && apt-key add /tmp/llvm-snapshot.gpg.key                                    \
 && DEBIAN_FRONTEND=noninteractive apt-get update                             \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        clang-format-4.0                                                      \
 && apt-get clean                                                             \
                                                                              \
 && cd /tmp/               && find . -delete                                  \
 && cd /var/lib/apt/lists/ && find . -delete                                  \
 && cd /var/tmp/           && find . -delete

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                                                   \
      org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
