#!/bin/bash

ENTRY_POINT="/tmp/dock_chrome_entry_point.sh"

PARAMS=$@
echo "PARAMS = ${PARAMS}"

cat > ${ENTRY_POINT} << EOF
#!/bin/bash
groupadd -g $(getent group $USER | cut -d: -f3) $USER
useradd -m -g $USER -G sudo -N -u $UID $USER
chown $USER:$USER /home/$USER
/bin/su $USER -c "google-chrome ${PARAMS}"

EOF

chmod +x ${ENTRY_POINT}
VOLUMES="-v ${ENTRY_POINT}:${ENTRY_POINT}:ro"
VOLUMES="${VOLUMES} -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm"
VOLUMES="${VOLUMES} -v $HOME/dock/chrome:/home/$USER"

docker run -d --entrypoint=${ENTRY_POINT} ${VOLUMES} -e DISPLAY=$DISPLAY approximator/chrome
