FROM ubuntu:xenial

RUN DEBIAN_FRONTEND=noninteractive apt update                             \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
        ca-certificates            \
        g++                        \
        gcc                        \
        libgl1-mesa-glx            \
        libglib2.0-0               \
        make                       \
        python                     \
        wget                       \
        zlib1g

RUN cd /tmp \
 && wget https://github.com/approximator/Dockerfiles/releases/download/qtv5.10.1/patchelf_0.10-1_amd64.deb \
 && wget https://github.com/approximator/Dockerfiles/releases/download/qtv5.10.1/qbs_1.10.1-approximator1_amd64.deb \
 && wget https://github.com/approximator/Dockerfiles/releases/download/qtv5.10.1/qt_5.10.1-approximator1_amd64.deb \
 && wget https://github.com/approximator/Dockerfiles/releases/download/qtv5.10.1/cmake_3.11.4-xenial-approximator1_amd64.deb \
 && cd /usr/local/bin/ && wget -O gosu https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64 \
 && dpkg -i /tmp/cmake_3.11.4-xenial-approximator1_amd64.deb \
 && dpkg -i /tmp/qt_5.10.1-approximator1_amd64.deb         \
 && dpkg -i /tmp/qbs_1.10.1-approximator1_amd64.deb        \
 && dpkg -i /tmp/patchelf_0.10-1_amd64.deb                 \
 && chmod +x /usr/local/bin/gosu                           \
 && cd /tmp/               && find . -delete               \
 && cd /var/lib/apt/lists/ && find . -delete               \
 && cd /var/tmp/           && find . -delete

ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                   \
      org.label-schema.build-date=$BUILD_DATE  \
      org.label-schema.vcs-ref=$VCS_REF        \
      org.label-schema.vcs-type="git"          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"