FROM ubuntu:16.04

ENV PYCHARM_HOME=/etc/pycharm
ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ADD common/setup.sh /tmp/setup.sh

RUN /tmp/setup.sh                                 \
 && DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    gcc                        \
    git                        \
    libfreetype6-dev           \
    libxft-dev                 \
    libxml2-dev                \
    libxrender1                \
    libxslt1-dev               \
    libxtst6                   \
    openjdk-8-jre              \
    pkg-config                 \
    python                     \
    python-dev                 \
    python-pip                 \
    python-setuptools          \
    python3                    \
    python3-dev                \
    python3-pip                \
    python3-setuptools         \
    zlib1g-dev                 \
 && apt-get clean              \
                               \
 && pip3 install -U pip        \
 && pip2 install -U pip        \
 && pip install -U             \
    wheel virtualenv           \
 && pip3 install -U            \
    wheel virtualenv           \
                               \
 && wget -P /tmp/ https://download.jetbrains.com/python/pycharm-community-2016.3.tar.gz \
 && mkdir ${PYCHARM_HOME}                                                       \
 && tar -xzvf /tmp/pycharm-community-2016.3.tar.gz -C ${PYCHARM_HOME} --strip=1 \
                                                                                \
 && cd /tmp/               && find . -delete                                    \
 && cd /var/lib/apt/lists/ && find . -delete                                    \
 && cd /var/tmp/           && find . -delete

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                                                   \
      org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
