FROM ubuntu:bionic

ENV DOWNLOAD_URL=https://download.jetbrains.com/python/pycharm-community-2019.3.3.tar.gz
ENV PYCHARM_HOME=/etc/pycharm
ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ADD common/setup.sh /tmp/setup.sh

RUN /tmp/setup.sh                                 \
 && DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    gcc                        \
    git                        \
    libfreetype6-dev           \
    libxft-dev                 \
    libxml2-dev                \
    libxrender1                \
    libxslt1-dev               \
    libxtst6                   \
    openjdk-8-jre              \
    pkg-config                 \
    python3.6                  \
    python3.7                  \
    python3-dev                \
    python3-pip                \
    python3-setuptools         \
    zlib1g-dev                 \
 && apt-get clean              \
                               \
 && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 100 \
 && python3 -m pip install -U  \
    setuptools wheel virtualenv\
                               \
 && wget -P /tmp/ -O /tmp/pycharm.tar.gz ${DOWNLOAD_URL}                       \
 && mkdir ${PYCHARM_HOME}                                                      \
 && tar -xzvf /tmp/pycharm.tar.gz -C ${PYCHARM_HOME} --strip=1                 \
 && chmod +x /usr/local/bin/gosu                                               \
 && cd /tmp/               && find . -delete                                   \
 && cd /var/lib/apt/lists/ && find . -delete                                   \
 && cd /var/tmp/           && find . -delete


ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                                                   \
      org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
