#!/bin/bash

: ${PYCHARM_VERSION:="latest"}
: ${ADDITIONAL_VOLUMES:=""}

VOLUMES="${ADDITIONAL_VOLUMES} -v $PWD:$PWD -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm"

if [ "/home/$USER" != "$PWD" ]; then
    VOLUMES="${VOLUMES} -v $HOME/dock/pych:/home/$USER"
fi

docker run -d ${VOLUMES} -e DISPLAY=$DISPLAY -e HOST_USER_ID=$(id -u) -e HOST_USER_GROUP_ID=$(id -g) -e HOST_USER_NAME=$USER approximator/pycharm:$PYCHARM_VERSION /etc/pycharm/bin/pycharm.sh "$@"
