#!/bin/bash

VOLUMES="-v $PWD:$PWD"
VOLUMES="${VOLUMES} -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm"
VOLUMES="${VOLUMES} -v $HOME/dock/pych:/home/$USER"

docker run -d ${VOLUMES} -e DISPLAY=$DISPLAY -e HOST_USER_ID=$(id -u) -e HOST_USER_GROUP_ID=$(id -g) -e HOST_USER_NAME=$USER  approximator/pycharm /etc/pycharm/bin/pycharm.sh
