FROM approximator/qt:5.7.0
MAINTAINER alex@nls.la

RUN cd /tmp                                                                \
 && git clone -b v1.5.1 git://code.qt.io/qt-labs/qbs.git                    \
 && git clone https://github.com/NixOS/patchelf.git patchelf               \
 && qmake -r qbs/qbs.pro                                                   \
 && make -j5                                                               \
 && make install                                                           \
                                                                           \
 && cd /tmp                                                                \
 && cd patchelf && ./bootstrap.sh && ./configure                           \
 && make -j5 && make install                                               \
                                                                           \
 && cd /tmp/               && find . -delete                               \
 && cd /var/lib/apt/lists/ && find . -delete                               \
 && cd /var/tmp/           && find . -delete

ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
