FROM approximator/qt:5.10.1

RUN DEBIAN_FRONTEND=noninteractive apt update                             \
 && DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
        ca-certificates            \
        g++                        \
        gcc                        \
        libgl1-mesa-glx            \
        libglib2.0-0               \
        make                       \
        python                     \
        autoconf                         \
        automake                         \
        bison                            \
        ca-certificates                  \
        checkinstall                     \
        cmake                            \
        flex                             \
        g++                              \
        gdb                              \
        git                              \
        gperf                            \
        libasound2-dev                   \
        libcap-dev                       \
        libdbus-1-dev                    \
        libegl1-mesa-dev                 \
        libfontconfig1-dev               \
        libfreetype6-dev                 \
        libgl1-mesa-glx                  \
        libglib2.0-0                     \
        libglu1-mesa-dev                 \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer1.0-0                \
        libicu-dev                       \
        libnss3-dev                      \
        libpci-dev                       \
        libpulse-dev                     \
        libssl-dev                       \
        libudev-dev                      \
        libx11-dev                       \
        libx11-xcb-dev                   \
        libxcb-glx0-dev                  \
        libxcb1-dev                      \
        libxcomposite-dev                \
        libxcursor-dev                   \
        libxdamage-dev                   \
        libxext-dev                      \
        libxfixes-dev                    \
        libxi-dev                        \
        libxrandr-dev                    \
        libxrender-dev                   \
        libxslt-dev                      \
        libxss-dev                       \
        libxtst-dev                      \
        wget                             \
        zlib1g

RUN cd /tmp \
 && wget https://github.com/approximator/Dockerfiles/releases/download/qtv5.10.1/qtcreator_4.6.2-approximator1_amd64.deb \
 && dpkg -i qtcreator_4.6.2-approximator1_amd64.deb        \
 && cd /tmp/               && find . -delete               \
 && cd /var/lib/apt/lists/ && find . -delete               \
 && cd /var/tmp/           && find . -delete

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                   \
      org.label-schema.build-date=$BUILD_DATE  \
      org.label-schema.vcs-ref=$VCS_REF        \
      org.label-schema.vcs-type="git"          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
