FROM approximator/qtcreator:latest
MAINTAINER alex@nls.la

RUN apt-get update                                 \
 && apt-get purge -y gdb                           \
 && apt-get install --no-install-recommends -y     \
        dh-autoreconf                              \
        gcc-arm-none-eabi                          \
        gdb-arm-none-eabi                          \
        libnewlib-dev                              \
        libstdc++-arm-none-eabi-newlib             \
        libusb-1.0.0-dev                           \
                                                   \
 && cd /tmp/                                       \
 && git clone https://github.com/texane/stlink.git \
 && cd stlink                                      \
 && cmake -DCMAKE_BUILD_TYPE=Release .             \
 && make -j4                                       \
 && make install                                   \
                                                   \
 && apt-get clean                                  \
 && cd /tmp/               && find . -delete       \
 && cd /var/lib/apt/lists/ && find . -delete       \
 && cd /var/tmp/           && find . -delete

ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
