FROM approximator/qt:5.7.0

ADD common/entrypoint.sh /usr/local/bin/entrypoint.sh
ADD common/setup.sh /tmp/setup.sh

RUN /tmp/setup.sh && cd /tmp                                                   \
 && git clone --recursive -b v4.0.2 https://code.qt.io/qt-creator/qt-creator.git \
 && qmake -v                                                                   \
 && mkdir /tmp/qt-creator-build                                                \
 && cd qt-creator-build                                                        \
 && qmake -r ../qt-creator/qtcreator.pro                                       \
 && make -j5                                                                   \
 && make install INSTALL_ROOT=/usr                                             \
                                                                               \
 && cd /tmp/               && find . -delete                                   \
 && cd /var/lib/apt/lists/ && find . -delete                                   \
 && cd /var/tmp/           && find . -delete

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer=alex@nls.la                                                   \
      org.label-schema.build-date=$BUILD_DATE                                  \
      org.label-schema.vcs-ref=$VCS_REF                                        \
      org.label-schema.vcs-type="git"                                          \
      org.label-schema.vcs-url="https://github.com/approximator/Dockerfiles"
