name: Update Dockerfiles

on:
  push:

  schedule:
    - cron: "0 5 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_URL: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel requests markdownify semver gitpython PyGithub

      - name: Update Dockerfiles
        id: updater
        run: |
          python common/UpdateImage.py
